language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
env:
  - ORG_GRADLE_PROJECT_googleClientVersion="+" ORG_GRADLE_PROJECT_mapsengineClientVersion="+"
before_script: cd java
notifications:
  email:
    - mdr-eng@google.com
